// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukdzoapwfritldskfzxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZHpvYXB3ZnJpdGxkc2tmenhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Mzc5OTcsImV4cCI6MjA2NzExMzk5N30.KMj-InYkxE9cHVpZgJpZvP9OB_YF2RkMQumlks-P2sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});